import turtle

class Turtle_new(turtle.Turtle):
    def box(self, pos_x, pos_y, x, y, color):
        self.penup()
        self.goto(pos_x, pos_y)
        self.pendown()
        self.speed('normal')
        self.color(color)
        self.begin_fill()
        self.fd(x)
        self.left(90)
        self.fd(y)
        self.left(90)
        self.fd(x)
        self.left(90)
        self.fd(y)
        self.left(90)
        self.end_fill()

    def merong(self, pos_x, pos_y):
        # 입 모양
        self.penup()
        self.goto(pos_x, pos_y)
        self.pendown()
        self.begin_fill()
        self.fd(70)
        self.left(90)
        self.fd(5)
        self.left(90)
        self.fd(70)
        self.left(90)
        self.fd(5)
        self.left(90)
        self.end_fill()
        # 메롱
        self.pensize(3)
        self.fd(20)
        self.right(90)
        self.fd(30)
        self.left(90)
        self.fd(30)
        self.left(90)
        self.fd(30)
        self.left(90)
        self.begin_fill()
        self.fd(20)
        self.left(90)
        self.fd(20)
        self.left(90)
        self.fd(10)
        self.left(90)
        self.fd(20)
        self.right(90)
        self.end_fill()

    def print_provoke(self, pos_x, pos_y, color, str):
        self.penup()
        self.goto(pos_x, pos_y)
        self.pendown()
        self.color(color)
        self.write(str, font=("Consolas", 20, "bold"))

    def smile(self, pos_x, pos_y, length, heading, color):
        self.penup()
        self.goto(pos_x, pos_y)
        self.pendown()
        self.speed('normal')
        self.color(color)
        self.begin_fill()
        self.setheading(heading)
        self.fd(15)
        self.right(90)
        self.fd(length)
        self.right(90)
        self.fd(15)
        self.right(90)
        self.fd(5)
        self.right(90)
        self.fd(10)
        self.left(90)
        self.fd(length-10)
        self.left(90)
        self.fd(10)
        self.right(90)
        self.fd(5)
        self.right(90)
        self.end_fill()

    def boltouch(self, pos_x, pos_y, length, color):
        self.penup()
        self.goto(pos_x, pos_y)
        self.pendown()
        self.speed('normal')
        self.color(color)
        self.begin_fill()
        self.circle(length)
        self.end_fill()